#
NUMERO1=5
NUMERO2=10
#OPERACIONES BASICAS
#SUMA, RESTA, MULTIPLICACION, DIVISION, POTENCIA
SUMA=NUMERO1 + NUMERO2
RESTA=NUMERO1 - NUMERO2
MULTIPLICACION = NUMERO1 * NUMERO2
DIVISION = NUMERO1 / NUMERO2
POTENCIA = NUMERO1**NUMERO2

#MOSTRAR RESULTADOS
print(SUMA)
print(RESTA)
print(MULTIPLICACION)
print(DIVISION)
print(POTENCIA)
